In [112]:
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [66]:
df =pd.read_csv('/Users/bangjiyun/3rd_project/year/df.csv')

# 데이터 전처리

In [67]:
df.rename(columns = {'환자수' : '2017_환자수'}, inplace = True)
df.rename(columns = {'내원일수' : '2017_내원일수'}, inplace = True)
df.rename(columns = {'청구건수' : '2017_청구건수'}, inplace = True)
df.rename(columns = {'요양급여비용총액' : '2017_요양급여비용총액'}, inplace = True)
df.rename(columns = {'보험자부담금' : '2017_보험자부담금'}, inplace = True)

df.rename(columns = {'환자수.1' : '2018_환자수'}, inplace = True)
df.rename(columns = {'환자수.2' : '2019_환자수'}, inplace = True)
df.rename(columns = {'환자수.3' : '2020_환자수'}, inplace = True)
df.rename(columns = {'환자수.4' : '2021_환자수'}, inplace = True)

df.rename(columns = {'내원일수.1' : '2018_내원일수'}, inplace = True)
df.rename(columns = {'내원일수.2' : '2019_내원일수'}, inplace = True)
df.rename(columns = {'내원일수.3' : '2020_내원일수'}, inplace = True)
df.rename(columns = {'내원일수.4' : '2021_내원일수'}, inplace = True)

df.rename(columns = {'청구건수.1' : '2018_청구건수'}, inplace = True)
df.rename(columns = {'청구건수.2' : '2019_청구건수'}, inplace = True)
df.rename(columns = {'청구건수.3' : '2020_청구건수'}, inplace = True)
df.rename(columns = {'청구건수.4' : '2021_청구건수'}, inplace = True)

df.rename(columns = {'요양급여비용총액.1' : '2018_요양급여비용총액'}, inplace = True)
df.rename(columns = {'요양급여비용총액.2' : '2019_요양급여비용총액'}, inplace = True)
df.rename(columns = {'요양급여비용총액.3' : '2020_요양급여비용총액'}, inplace = True)
df.rename(columns = {'요양급여비용총액.4' : '2021_요양급여비용총액'}, inplace = True)

df.rename(columns = {'보험자부담금.1' : '2018_보험자부담금'}, inplace = True)
df.rename(columns = {'보험자부담금.2' : '2019_보험자부담금'}, inplace = True)
df.rename(columns = {'보험자부담금.3' : '2020_보험자부담금'}, inplace = True)
df.rename(columns = {'보험자부담금.4' : '2021_보험자부담금'}, inplace = True)
df

,항목,성별구분,연령구분5세,2017_환자수,2017_내원일수,2017_청구건수,2017_요양급여비용총액,2017_보험자부담금,2018_환자수,2018_내원일수,...,2020_환자수,2020_내원일수,2020_청구건수,2020_요양급여비용총액,2020_보험자부담금,2021_환자수,2021_내원일수,2021_청구건수,2021_요양급여비용총액,2021_보험자부담금
0,지방간,남,5세미만,30,109,77,"19,839","17,061",29,95,...,48,158,94,"44,478","35,751",45,164,116,"38,040","31,916"
1,지방간,남,5_9세,506,"1,002",981,"52,165","26,818",580,"1,131",...,534,"1,104","1,080","96,094","52,242",898,"1,778","1,754","149,399","81,957"
2,지방간,남,10_14세,"2,443","5,152","5,075","241,508","133,760","2,645","5,656",...,"2,415","5,751","5,505","428,328","247,173","5,093","10,702","10,603","792,735","442,634"
3,지방간,남,15_19세,"5,898","12,370","12,093","541,935","315,538","5,807","11,727",...,"5,395","10,953","10,744","740,496","435,793","6,928","14,379","14,197","1,009,661","596,978"
4,지방간,남,20_24세,"7,017","13,591","13,327","596,911","348,119","7,025","13,142",...,"7,858","14,684","14,389","995,549","597,693","9,008","16,852","16,702","1,212,606","728,232"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7596,환경성질환,여,60_64세,"232,870","559,001","541,979","12,732,701","8,595,145","253,392","598,464",...,"216,417","498,109","486,757","12,826,959","8,601,092","174,903","397,224","388,141","11,036,747","7,378,514"
7597,환경성질환,여,65_69세,"176,926","461,053","448,657","10,036,419","7,466,919","192,782","493,422",...,"166,534","417,954","408,064","10,501,758","7,863,418","139,663","343,257","335,253","9,310,191","6,907,153"
7598,환경성질환,여,70_74세,"143,378","404,272","388,688","9,498,922","7,107,154","150,257","415,510",...,"128,280","346,875","338,021","8,968,701","6,724,035","104,715","281,193","273,569","7,777,488","5,756,192"
7599,환경성질환,여,75_79세,"123,730","393,854","357,972","11,289,549","8,478,400","136,410","425,485",...,"111,488","334,462","317,913","9,639,883","7,259,243","84,676","247,046","234,443","7,562,770","5,601,143"
7600,환경성질환,여,80세이상,"109,293","478,128","332,602","21,763,369","16,256,764","122,334","498,472",...,"116,053","449,081","347,288","20,103,859","15,118,438","98,759","387,111","294,573","17,641,233","13,150,621"

# 결측치 해결(성별구분)

In [68]:
df['성별구분'][df['성별구분'] == '여'] = 1 
df['성별구분'][df['성별구분'] == '남'] = 0

In [69]:
df['성별구분'].value_counts()

1    3903
0    3698
Name: 성별구분, dtype: int64

# 결측치 해결 - '-' 이거를 '0'으로

In [70]:
temp = df.iloc[:,3:]
temp.describe()
temp.replace('-',0,inplace=True, regex=True)

/var/folders/0_/gqzzfsxd1391jx3x0k4j_lhm0000gn/T/ipykernel_27690/972473274.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.replace('-',0,inplace=True, regex=True)

In [71]:
temp.describe()

,2017_환자수,2017_내원일수,2017_청구건수,2017_요양급여비용총액,2017_보험자부담금,2018_환자수,2018_내원일수,2018_청구건수,2018_요양급여비용총액,2018_보험자부담금,...,2020_환자수,2020_내원일수,2020_청구건수,2020_요양급여비용총액,2020_보험자부담금,2021_환자수,2021_내원일수,2021_청구건수,2021_요양급여비용총액,2021_보험자부담금
count,7601,7601,7601,7601,7601,7601,7601,7601,7601,7601,...,7601,7601,7601,7601,7601,7601,7601,7601,7601,7601
unique,4827,6054,5808,7247,7218,4884,6073,5826,7256,7216,...,4852,6046,5810,7249,7228,4848,6031,5813,7245,7217
top,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
freq,98,85,85,85,85,87,87,87,87,87,...,109,109,109,109,109,99,95,95,95,95

# 모두 int로 변환해버리귀

In [81]:
df.iloc[:,3:] = df.iloc[:,3:].replace(',','',regex=True)
df.iloc[:,3:] = df.iloc[:,3:].astype('int')

In [85]:
df.to_csv('/Users/bangjiyun/3rd_project/year/df.csv',index=False, header=True)

# 데이터 쪼개기

In [117]:
df = pd.read_csv('/Users/bangjiyun/3rd_project/year/df.csv')

In [125]:
df_2017 = df.iloc[:,:8]
df_2017.iloc[:,3:9] = df_2017.iloc[:,3:9].astype('int')

df_2017['2017_본인부담금'] = df['2017_요양급여비용총액'] - df['2017_보험자부담금']
df_2017['2017_연도'] = 2017
df_2017.to_csv("/Users/bangjiyun/3rd_project/year/2017.csv", header=True,index=False)

In [126]:
df_2017

,항목,성별구분,연령구분5세,2017_환자수,2017_내원일수,2017_청구건수,2017_요양급여비용총액,2017_보험자부담금,2017_본인부담금,2017_연도
0,지방간,0,5세미만,30,109,77,19839,17061,2778,2017
1,지방간,0,5_9세,506,1002,981,52165,26818,25347,2017
2,지방간,0,10_14세,2443,5152,5075,241508,133760,107748,2017
3,지방간,0,15_19세,5898,12370,12093,541935,315538,226397,2017
4,지방간,0,20_24세,7017,13591,13327,596911,348119,248792,2017
...,...,...,...,...,...,...,...,...,...,...
7596,환경성질환,1,60_64세,232870,559001,541979,12732701,8595145,4137556,2017
7597,환경성질환,1,65_69세,176926,461053,448657,10036419,7466919,2569500,2017
7598,환경성질환,1,70_74세,143378,404272,388688,9498922,7107154,2391768,2017
7599,환경성질환,1,75_79세,123730,393854,357972,11289549,8478400,2811149,2017
7600,환경성질환,1,80세이상,109293,478128,332602,21763369,16256764,5506605,2017

In [138]:
df_2018 = df[['항목','성별구분','연령구분5세','2018_환자수','2018_내원일수','2018_청구건수','2018_요양급여비용총액','2018_보험자부담금']] 
df_2018.iloc[:,3:] = df_2018.iloc[:,3:].astype('int')

df_2018['2018_본인부담금'] = df['2018_요양급여비용총액'] - df['2018_보험자부담금']
df_2018['2018_연도'] = 2018
df_2018.to_csv("/Users/bangjiyun/3rd_project/year/2018.csv", header=True,index=False)

In [137]:
df_2018

,항목,성별구분,연령구분5세,2018_환자수,2018_내원일수,2018_청구건수,2018_요양급여비용총액,2018_보험자부담금,2018_본인부담금,2018_연도
0,지방간,0,5세미만,29,95,77,14382,11207,3175,2018
1,지방간,0,5_9세,580,1131,1090,85541,49170,36371,2018
2,지방간,0,10_14세,2645,5656,5568,340313,190672,149641,2018
3,지방간,0,15_19세,5807,11727,11454,654519,388993,265526,2018
4,지방간,0,20_24세,7025,13142,12852,732827,432558,300269,2018
...,...,...,...,...,...,...,...,...,...,...
7596,환경성질환,1,60_64세,253392,598464,581628,14426672,9711334,4715338,2018
7597,환경성질환,1,65_69세,192782,493422,480909,11436326,8647854,2788472,2018
7598,환경성질환,1,70_74세,150257,415510,400893,10328687,7839331,2489356,2018
7599,환경성질환,1,75_79세,136410,425485,393169,12718529,9647824,3070705,2018
7600,환경성질환,1,80세이상,122334,498472,361280,23252906,17463879,5789027,2018

In [143]:
df_2019 = df[['항목','성별구분','연령구분5세','2019_환자수','2019_내원일수','2019_청구건수','2019_요양급여비용총액','2019_보험자부담금']] 
df_2019.iloc[:,3:] = df_2019.iloc[:,3:].astype('int')

df_2019['2019_본인부담금'] = df['2019_요양급여비용총액'] - df['2019_보험자부담금']
df_2019['2019_연도'] = 2019
df_2019.to_csv("/Users/bangjiyun/3rd_project/year/2019.csv", header=True,index=False)

In [142]:
df_2019

,항목,성별구분,연령구분5세,2019_환자수,2019_내원일수,2019_청구건수,2019_요양급여비용총액,2019_보험자부담금,2019_본인부담금,2019_연도
0,지방간,0,5세미만,35,186,121,40050,33636,6414,2019
1,지방간,0,5_9세,576,1075,1065,80519,43278,37241,2019
2,지방간,0,10_14세,2995,6501,6409,467445,259747,207698,2019
3,지방간,0,15_19세,6276,12649,12480,809814,472477,337337,2019
4,지방간,0,20_24세,8072,15038,14542,993508,593767,399741,2019
...,...,...,...,...,...,...,...,...,...,...
7596,환경성질환,1,60_64세,257949,600879,584855,15396068,10326746,5069322,2019
7597,환경성질환,1,65_69세,190882,481559,468618,12186559,9178198,3008361,2019
7598,환경성질환,1,70_74세,149315,405678,393578,10520629,7928240,2592389,2019
7599,환경성질환,1,75_79세,131899,395886,372942,11868231,8998265,2869966,2019
7600,환경성질환,1,80세이상,126786,497878,373745,23408565,17593990,5814575,2019

In [146]:
df_2020 = df[['항목','성별구분','연령구분5세','2020_환자수','2020_내원일수','2020_청구건수','2020_요양급여비용총액','2020_보험자부담금']] 
df_2020.iloc[:,3:] = df_2020.iloc[:,3:].astype('int')

df_2020['2020_본인부담금'] = df['2020_요양급여비용총액'] - df['2020_보험자부담금']
df_2020['2020_연도'] = 2020
df_2020.to_csv("/Users/bangjiyun/3rd_project/year/2020.csv", header=True,index=False)

In [145]:
df_2020

,항목,성별구분,연령구분5세,2020_환자수,2020_내원일수,2020_청구건수,2020_요양급여비용총액,2020_보험자부담금,2020_본인부담금,2020_연도
0,지방간,0,5세미만,48,158,94,44478,35751,8727,2020
1,지방간,0,5_9세,534,1104,1080,96094,52242,43852,2020
2,지방간,0,10_14세,2415,5751,5505,428328,247173,181155,2020
3,지방간,0,15_19세,5395,10953,10744,740496,435793,304703,2020
4,지방간,0,20_24세,7858,14684,14389,995549,597693,397856,2020
...,...,...,...,...,...,...,...,...,...,...
7596,환경성질환,1,60_64세,216417,498109,486757,12826959,8601092,4225867,2020
7597,환경성질환,1,65_69세,166534,417954,408064,10501758,7863418,2638340,2020
7598,환경성질환,1,70_74세,128280,346875,338021,8968701,6724035,2244666,2020
7599,환경성질환,1,75_79세,111488,334462,317913,9639883,7259243,2380640,2020
7600,환경성질환,1,80세이상,116053,449081,347288,20103859,15118438,4985421,2020

In [149]:
df_2021 = df[['항목','성별구분','연령구분5세','2021_환자수','2021_내원일수','2021_청구건수','2021_요양급여비용총액','2021_보험자부담금']] 
df_2021.iloc[:,3:] = df_2021.iloc[:,3:].astype('int')

df_2021['2021_본인부담금'] = df['2021_요양급여비용총액'] - df['2021_보험자부담금']
df_2021['2021_연도'] = 2021
df_2021.to_csv("/Users/bangjiyun/3rd_project/year/2021.csv", header=True,index=False)

In [148]:
df_2021

,항목,성별구분,연령구분5세,2021_환자수,2021_내원일수,2021_청구건수,2021_요양급여비용총액,2021_보험자부담금,2021_본인부담금,2021_연도
0,지방간,0,5세미만,45,164,116,38040,31916,6124,2021
1,지방간,0,5_9세,898,1778,1754,149399,81957,67442,2021
2,지방간,0,10_14세,5093,10702,10603,792735,442634,350101,2021
3,지방간,0,15_19세,6928,14379,14197,1009661,596978,412683,2021
4,지방간,0,20_24세,9008,16852,16702,1212606,728232,484374,2021
...,...,...,...,...,...,...,...,...,...,...
7596,환경성질환,1,60_64세,174903,397224,388141,11036747,7378514,3658233,2021
7597,환경성질환,1,65_69세,139663,343257,335253,9310191,6907153,2403038,2021
7598,환경성질환,1,70_74세,104715,281193,273569,7777488,5756192,2021296,2021
7599,환경성질환,1,75_79세,84676,247046,234443,7562770,5601143,1961627,2021
7600,환경성질환,1,80세이상,98759,387111,294573,17641233,13150621,4490612,2021